---
- name: grab openstack facts
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
  loop: "{{result.ansible_facts.openstack_servers}}"

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.deployment_name }}"
  loop: "{{result.ansible_facts.openstack_servers}}"