---
- name: Set service startup mode to auto and ensure it is started
  win_service:
    name: '{{ service_name }}'
    start_mode: auto
    state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
