---
- name: Install packages
  win_chocolatey:
    name: '{{ package_name }}'
    state: present
    params: '{{ parameters }}'
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
