servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend_servers
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: app_servers
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: app_servers
    meta:
      - { group: apps, deployment_name: QA}
  appdb1:
    name: appdb1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db_servers
    meta:
      - { group: appdbs, deployment_name: QA}