---
- name: copy repo template
  template:
    src: repo.j2
    dest: "{{repo_file_path}}/{{repo_file_name}}"
    mode: 0644

- name: install common packages
  yum:
    name: "{{ item }}" 
    state: present
  with_items: "{{common_packages}}"

    
