---
- name: ensure groups exist
  win_domain_group:
    name: '{{ item.group_name }}'
    scope: global
  loop: '{{ user_info }}'

- name: create users
  win_domain_user:
    name: '{{ item.name }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.surname }}'
    password: '{{ item.password }}'
    email: '{{ item.email }}'
    state: present
    groups: '{{ item.group_name }}'
  loop: '{{ user_info }}'
