---
- name: haproxy
  hosts: frontends
  gather_facts: no
  become: true

  tasks:
  - name: (haproxy) install packages
    yum:
      name: "{{ item }}"
      state: present 
    with_items:
      - httpie
      - haproxy
  
  - name: (haproxy) enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    register: haproxy_enabled
    with_items:
      - haproxy
    
  - name: (haproxy) configure haproxy
    template:
      src: ../templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    when: haproxy_enabled
    notify:
      - restart_haproxy
  
  handlers:
    - name: restart_haproxy
      service:
        name: haproxy
        state: restarted