---
- name: build_dc
  hosts: windows
  gather_facts: true
  become: true
  roles:
    - {name: win_ad_install }

  tasks:
    - name: test
      raw: "nltest /dclist:"
      register: result

    - debug: msg="{{result}}"
