---
- name: install_ssh_server
  hosts: windows
  gather_facts: true
  become: true
  tasks:

    - name: install shh server
      include_role:
        name: win_package_install
    
    - name: set ssh server to auto start
      include_role:
        name: win_service_config
    
    - name: create firewall rule for ssh
      include_role:
        name: win_firewall