---

- include: prep_servers.yml
  when: prep_servers

- include: build_db_server.yml
  when: build_db

- include: build_app_server.yml
  when: build_app

- include: build_frontend_server.yml
  when: build_frontend



