---
- name: install ad domain services
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: promote dc
  win_domain:
   dns_domain_name: "{{ad_domain_name}}" 
   safe_mode_password: "{{ansible_password}}" 
  register: promoted

- name: restart_server
  win_reboot:
  when: promoted is changed


